name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    tags:
      - '*'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "This job's status is ${{ job.status }}."
      - run: zip -r mycoolapp_main mycoolapp/src/main

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Create Release
        id: create_release_id
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
    
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release_id.outputs.upload_url }}
            asset_path: mycoolapp_main.zip
            asset_name: mycoolapp_main.zip
            asset_content_type: application/zip

          

