name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    tags:
      - '*'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "This job's status is ${{ job.status }}."
      - run: zip -r mycoolapp_main mycoolapp/src/main

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Upload more zips
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: mycoolapp_main
            tag: ${{ github.ref }}
            overwrite: true
            body: "Uploading more zips"
          

